# Generated by Django 3.2.5 on 2021-08-20 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=45)),
                ('nit', models.CharField(max_length=12)),
                ('dpi', models.CharField(max_length=16)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(max_length=45)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.customer')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=45)),
                ('nit', models.CharField(max_length=12)),
                ('dpi', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.order')),
                ('product_factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productfactory')),
            ],
        ),
        migrations.CreateModel(
            name='LoadArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('units', models.IntegerField()),
                ('status', models.CharField(max_length=45)),
                ('product_factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productfactory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
        ),
    ]
