# Generated by Django 3.2.5 on 2021-08-27 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_customer_loadarticle_order_orderdetail_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargarArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('unidades', models.IntegerField()),
                ('estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=45)),
                ('nit', models.CharField(max_length=12)),
                ('dpi', models.CharField(max_length=16)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descuento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('tipo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(max_length=45)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=45)),
                ('moneda', models.CharField(max_length=3)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('imagen', models.CharField(max_length=255)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoFabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existencia', models.IntegerField()),
                ('min_existencia', models.IntegerField()),
                ('max_existencia', models.IntegerField()),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.fabrica')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=45)),
                ('nit', models.CharField(max_length=12)),
                ('dpi', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='loadarticle',
            name='product_factory',
        ),
        migrations.RemoveField(
            model_name='loadarticle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product_factory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productfactory',
            name='factory',
        ),
        migrations.RemoveField(
            model_name='productfactory',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Factory',
        ),
        migrations.DeleteModel(
            name='LoadArticle',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductFactory',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='pedidodetalle',
            name='producto_fabrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productofabrica'),
        ),
        migrations.AddField(
            model_name='cargararticulo',
            name='producto_fabrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productofabrica'),
        ),
        migrations.AddField(
            model_name='cargararticulo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.usuario'),
        ),
    ]
